logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/notemax
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

keycloak:
  realm: notemax
  auth-server-url: http://localhost:8081
  resource: notemax-client
  credentials:
    secret: k7LCecIUFVlbSagjIxAv1xOjt4RL3iI8
  bearer-only: true
  use-resource-role-mappings: true

auth:
  jwt:
    secret: aWx1aXNkZmxpYW5maWZtczEyMzEyMzE0emxtY3p4Y2tvc2FrbWRvYWtkbW0xMjMxNTQzNjQ2NQ==
  accessToken:
    expiration: 86400000
  refreshToken:
    expiration: 1209600000

cookie:
  domain: localhost
  max-age: 345600